spring:
  application:
    name: flyway-demo
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
      - classpath:db/rollback
    validate-on-migrate: true

# Custom Rollback Configuration
flyway:
  rollback:
    enabled: true
    auto-rollback-on-failure: false
    require-approval: false
    snapshot:
      enabled: true
      storage-path: ${user.home}/flyway-snapshots
      retention-days: 7
    audit:
      enabled: true
      table-name: flyway_rollback_audit

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,flyway,prometheus

# Logging
logging:
  level:
    com.example: DEBUG
    org.flywaydb: DEBUG

---
# Local Profile (H2) - Default
spring:
  config:
    activate:
      on-profile: local
      
  datasource:
    url: jdbc:h2:mem:flyway_demo;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
# MySQL Profile
spring:
  config:
    activate:
      on-profile: mysql
      
  datasource:
    url: jdbc:mysql://localhost:3306/flyway_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD:callicoder}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    
  flyway:
    rollback:
      snapshot:
        storage-path: ${java.io.tmpdir}/test-snapshots